export const ALL_EMPLOYEES_REQUEST = 'ALL_EMPLOYEES_REQUEST'
export const ALL_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS'
export const ALL_EMPLOYEES_FAIL = 'ADDALL_EMPLOYEES_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

