export const ALL_EMPLOYEES_REQUEST = 'ALL_EMPLOYEES_REQUEST'
export const ALL_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS'
export const ALL_EMPLOYEES_FAIL = 'ADDALL_EMPLOYEES_FAIL'
export const POST_EMPLOYEE_REQUEST = 'POST_EMPLOYEE_REQUEST'
export const POST_EMPLOYEE_SUCCESS = 'POST_EMPLOYEE_SUCCESS'
export const POST_EMPLOYEE_FAIL = 'POST_EMPLOYEE_FAIL'
export const DELETE_EMPLOYEE_REQUEST = 'POST_EMPLOYEE_FAIL'
export const DELETE_EMPLOYEE_SUCCESS = 'POST_EMPLOYEE_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


